Repository YAPP-Github/mukpat-client, pull requests merged in 2023-07, with the labels that each got.

#65 feature/FE-043: 로그인 후 프로필 이상문제 해결
  next.config.js
  src/api/user/api.ts
  src/app/login/api/login.ts
  src/app/login/hooks/useLogin/useLogin.ts
Labels: enhancement

#68 먹팟 v0.1 - 로그인 버그 수정
  next.config.js
  src/api/user/api.ts
  src/app/login/api/login.ts
  src/app/login/hooks/useLogin/useLogin.ts
Labels: enhancement

#67 feature/FE-011: 먹팟 생성페이지 Data Invalid error 해결
  src/app/write/components/AgeModal/AgeController.tsx
  src/app/write/components/AgeModal/AgeModal.tsx
  src/app/write/components/Counter/Counter.css.ts
  src/app/write/components/Form/FirstStep.tsx
  src/app/write/components/InputDate/InputDate.tsx
  src/app/write/components/MapModal/MapModal.tsx
  src/app/write/constants/index.ts
  src/app/write/hooks/usePostBoard.ts
  src/app/write/lib/schema.ts
  src/app/write/page.tsx
  src/app/write/style.css.ts
  src/app/write/types/index.ts
  src/components/Input/Input.tsx
Labels: enhancement

#66 feature/FE-044: MapConfirmButton disabled 처리
  src/components/Map/MapConfirmButton.tsx
Labels: enhancement

#70 feature/FE-051 : themeToken grey50 수정
  src/styles/theme.css.ts
Labels: enhancement

#75 feature/FE-055 : Google tag manager 연동 작업
  src/app/layout.tsx
Labels: ✨ feature

#72 Feature/fe-043 : 로그인 후 프로필 갱신 로직 수정
  src/api/board/hooks/useCancelJoinBoard.ts
  src/api/board/hooks/useDeleteBoard.ts
  src/api/board/hooks/useJoinBoard.ts
  src/api/common/hooks/index.ts
  src/api/hooks.ts
  src/api/user/api.ts
  src/api/user/hooks/index.ts
  src/api/user/hooks/useLogin.ts
  src/app/login/api/index.ts
  src/app/login/api/login.ts
  src/app/login/components/LoginButton/LoginButton.tsx
  src/app/login/components/LoginForm/LoginForm.tsx
  src/app/login/hooks/index.ts
  src/app/login/hooks/useLogin/useLogin.ts
  src/app/login/hooks/useLoginForm/useLoginForm.ts
  src/components/Header/Header.tsx
  src/components/Header/HeaderActions.tsx
  src/components/Header/HydratedHeaderActions.tsx
  src/hooks/index.ts
  src/hooks/useMutation/useMutation.ts
Labels: enhancement

#78 feature/FE-054 : breakpoints 추가
  src/styles/theme.css.ts
Labels: ✨ feature

#73 feature/FE-053 : Input 컴포넌트 fixed Height helper text 대응
  src/app/login/components/LoginForm/LoginForm.tsx
  src/components/Input/Input.css.ts
  src/components/Input/Input.tsx
  src/components/Input/InputErrorMessage.tsx
Labels: enhancement

#77 Feature/FE-041 : Map 컴포넌트 수정사항
  public/spriteIcons/marker.svg
  src/app/signup/components/EmailRequestSignUp/EmailRequestSignUp.tsx
  src/app/signup/components/MapButton/MapButton.css.ts
  src/app/signup/components/MapButton/MapButton.tsx
  src/app/signup/components/ProfileSetupSignUp/ProfileSetupSignUp.tsx
  src/app/signup/components/index.ts
  src/app/signup/hooks/useCommonForm/useCommonForm.ts
  src/app/signup/types/map.ts
  src/app/signup/types/signup.ts
  src/components/Button/Button.tsx
  src/components/Loading/Loading.css.ts
  src/components/Loading/Loading.tsx
  src/components/Map/Map.css.ts
  src/components/Map/Map.tsx
  src/components/Map/MapConfirmButton.tsx
  src/components/Map/MapSearchItem.tsx
  src/components/Map/MapSearchList.tsx
  src/components/Map/MapWrapper.tsx
  src/components/Map/contexts/MapContextProvider.tsx
  src/components/Map/hooks/useMap.ts
  src/components/Map/hooks/useMapListMarkers.ts
  src/components/Map/hooks/useMapPickMarker.ts
  src/components/Map/hooks/useMapSearchForm.ts
  src/components/Map/hooks/useSearchList.ts
  src/components/Map/types/index.ts
  src/components/Map/utils/mapMarkerUtils.ts
  src/components/Map/utils/mapSearchUtils.ts
  src/components/Map/utils/mapUtils.ts
  src/types/map.ts
Labels: enhancement

#80 Feature/FE-058: Dropdown radius 수정
  src/components/Dropdown/Dropdown.css.ts
Labels: 🎨 design

#82 Feature/fe-059 로그인 여부에 따른 기능제한 추가
  next.config.js
  src/api/user/api.ts
  src/api/user/hooks/index.ts
  src/api/user/hooks/useLogout.ts
  src/app/board/components/AsideSection/AsideSection.tsx
  src/app/home/components/HeroSection/HeroSection.tsx
  src/app/layout.tsx
  src/app/login/components/LoginForm/LoginForm.tsx
  src/components/Header/Header.tsx
  src/components/Header/LoginActions.tsx
  src/components/Header/UnloginActions.tsx
  src/hooks/index.ts
  src/hooks/useLoginRedirect/useLoginRedirect.ts
  src/providers/ProfileProvider.tsx
  src/providers/index.ts
  src/providers/server.ts
Labels: ✨ feature

#83 Feature/fe-057 : mobile 대응 먹팟 등록페이지 css 수정
  src/app/write/components/AgeModal/AgeController.tsx
  src/app/write/components/AgeModal/AgeModal.tsx
  src/app/write/components/Counter/Counter.tsx
  src/app/write/components/Form/FirstStep.tsx
  src/app/write/components/Form/Form.css.ts
  src/app/write/components/Form/SecondStep.tsx
  src/app/write/components/InputDate/InputDate.tsx
  src/app/write/components/MapModal/MapModal.tsx
  src/app/write/lib/schema.ts
  src/app/write/page.tsx
  src/app/write/style.css.ts
  src/components/Input/Input.css.ts
  src/components/Input/InputDropdown.tsx
  src/components/Input/schema.ts
  src/hooks/index.ts
  src/hooks/useMediaQuery/useMediaQuery.ts
Labels: ✨ feature

#89 Feature/fe-060 메인페이지 1.0 변경점 일부 적용
  src/app/home/components/BoardCard/BoardCard.css.ts
  src/app/home/components/BoardCard/BoardCard.tsx
  src/app/home/components/BoardCardListLoading/BoardCardListLoading.css.ts
  src/app/home/components/BoardSection/BoardSection.css.ts
  src/app/home/components/HeroSection/HeroSection.css.ts
  src/app/home/components/HeroSection/HeroSection.tsx
  src/app/home/constants/constants.ts
Labels: ✨ feature, 🎨 design

#100 Feature/fe-061 Dropdown 수정사항 반영
  src/components/BottomSheet/BottomSheet.css.ts
  src/components/BottomSheet/BottomSheet.tsx
  src/components/BottomSheet/BottomSheetView.tsx
  src/components/BottomSheet/hooks/useModalControl/useModalControl.ts
  src/components/Dropdown/Dropdown.css.ts
  src/components/Dropdown/DropdownBottomSheet.tsx
  src/components/Dropdown/DropdownButton.tsx
  src/components/Dropdown/DropdownItem.tsx
  src/components/Dropdown/DropdownMenu.tsx
  src/components/Dropdown/DropdownModal.tsx
  src/components/Dropdown/README.md
  src/components/Dropdown/contexts/DropdownMenuContext.tsx
  src/components/Dropdown/hooks/useDropdownBottomSheet/useDropdownBottomSheet.test.ts
  src/components/Dropdown/hooks/useDropdownBottomSheet/useDropdownBottomSheet.tsx
  src/components/Dropdown/index.ts
  src/components/Modal/Modal.css.ts
  src/components/Modal/Modal.tsx
  src/hooks/useClickOutside/useClickOutside.test.tsx
  src/hooks/useClickOutside/useClickOutside.ts
Labels: ✨ feature

#104 feature/FE-076: GTM userID 푸시 기능 추가
  .pnp.cjs
  .yarn/cache/@types-crypto-js-npm-4.1.1-1c4ce3312a-ea3d6a67b6.zip
  .yarn/cache/crypto-js-npm-4.1.1-38a3b8c19d-b3747c12ee.zip
  package.json
  src/components/Header/Header.tsx
  src/components/Header/HeaderDataLayer.tsx
  yarn.lock
Labels: ✨ feature

#101 Feature/fe-064 로고 교체 및 헤더 반응형 적용
  public/sprite.svg
  public/spriteIcons/feedback.svg
  src/app/login/page.tsx
  src/app/signup/page.tsx
  src/components/BottomButton/BottomButton.tsx
  src/components/Button/Button.css.ts
  src/components/Header/FeedbackAction.tsx
  src/components/Header/Header.css.ts
  src/components/Header/Header.tsx
  src/components/Header/HeaderActions.tsx
  src/components/Header/LoginActions.tsx
  src/components/Header/UnloginActions.tsx
  src/components/Logo/Logo.css.ts
  src/components/Logo/Logo.tsx
  src/components/Profile/Profile.css.ts
Labels: ✨ feature

#106 Feature/fe-079 : 페이지 전환 애니메이션 적용
  src/app/home/components/BoardSection/BoardSection.tsx
  src/app/home/components/HeroSection/HeroSection.tsx
  src/app/login/components/LoginWrapper/LoginWrapper.tsx
  src/styles/theme.css.ts
Labels: 🎨 design

#105 Feature/fe-069 메인페이지 반응형 적용 및 필터 추가
  public/sprite.svg
  public/spriteIcons/lightning.svg
  public/spriteIcons/pluswhite.svg
  public/spriteIcons/samsung.svg
  src/api/board/api.ts
  src/api/board/hooks/index.ts
  src/api/board/hooks/useBoardListQuery.ts
  src/api/board/hooks/useBoardRegions.ts
  src/api/board/queryKeys.ts
  src/api/board/types.ts
  src/app/error.tsx
  src/app/home/components/BoardCard/BoardCard.css.ts
  src/app/home/components/BoardCard/BoardCard.tsx
  src/app/home/components/BoardCardList/BoardCardList.css.ts
  src/app/home/components/BoardCardList/BoardCardList.tsx
  src/app/home/components/BoardCardListLoading/BoardCardListLoading.css.ts
  src/app/home/components/BoardCardListLoading/BoardCardListLoading.tsx
  src/app/home/components/BoardSection/BoardSection.css.ts
  src/app/home/components/BoardSection/BoardSection.tsx
  src/app/home/components/FloatingButton/FloatingButton.css.ts
  src/app/home/components/FloatingButton/FloatingButton.tsx
  src/app/home/components/HeroSection/HeroSection.css.ts
  src/app/home/components/HeroSection/HeroSection.tsx
  src/app/home/components/RegionsFilter/RegionsFilter.css.ts
  src/app/home/components/RegionsFilter/RegionsFilter.tsx
  src/app/home/components/RegionsFilter/RegionsFilterLoading.tsx
  src/app/home/components/index.ts
  src/app/home/constants/constants.ts
  src/app/home/hooks/index.ts
  src/app/home/hooks/useDetectSticky/useDetectSticky.ts
  src/app/home/hooks/useScrollDownState/useScrollDownState.test.ts
  src/app/home/hooks/useScrollDownState/useScrollDownState.ts
  src/app/home/store/index.ts
  src/app/home/store/useRegionFilterStore.ts
  src/app/page.tsx
  src/app/signup/page.tsx
  src/app/write/page.tsx
  src/components/Dropdown/Dropdown.css.ts
  src/components/Dropdown/DropdownButton.tsx
  src/components/Dropdown/DropdownMenu.tsx
  src/components/ErrorMessage/ErrorMessage.css.ts
  src/components/ErrorMessage/ErrorMessage.tsx
  src/components/Header/Header.tsx
  src/components/index.ts
  src/styles/theme.css.ts
Labels: ✨ feature

#109 hotfix: 메인페이지 navigation 안되는 문제 해결
  src/app/page.tsx
  src/components/Header/Header.tsx
Labels: 🐞 bug

#110 hotfix: 네비게이션 blocking 문제 해결 시도
  src/app/board/components/HydratedBoardDetail/HydratedBoardDetail.tsx
  src/app/home/components/HydratedBoardCardList/HydratedBoardCardList.tsx
Labels: 🐞 bug

#112 hotfix: 네비게이션 blocking 문제 해결 시도
  src/app/board/[id]/page.tsx
  src/app/home/components/BoardSection/BoardSection.tsx
Labels: 🐞 bug

#113 hotfix: 메인페이지 navigation 안되는 문제 해결 시도
  src/app/board/[id]/page.tsx
  src/app/home/components/BoardSection/BoardSection.tsx
Labels: 🐞 bug

#114 hotfix: 상세페이지 block 되는 문제 해결 시도
  next.config.js
  src/app/board/components/AsideSection/AsideSection.tsx
  src/app/board/components/BoardDetail/BoardDetail.tsx
  src/app/board/components/BottomSection/BottomSection.tsx
  src/app/board/components/DetailMenuButton/DetailMenuButton.tsx
  src/app/board/components/ParticipantsList/ParticipantsList.tsx
Labels: 🐞 bug

#115 hotfix: 상세페이지 block 되는 문제 해결 시도
  src/app/board/components/BoardDetail/BoardDetail.tsx
Labels: 🐞 bug

#117 hotfix: 주석처리된 코드 원상 복귀
  src/app/board/components/BoardDetail/BoardDetail.tsx
Labels: 🐞 bug

#119 hotfix: 배포 레포지토리 이동
  .github/workflows/team-push.yml
Labels: 🐞 bug, enhancement

#118 Feature/FE-045 : map 모바일 flow 추가
  .eslintrc.json
  src/app/login/components/LoginForm/LoginForm.css.ts
  src/components/Loading/Loading.css.ts
  src/components/Map/Map.css.ts
  src/components/Map/Map.tsx
  src/components/Map/MapConfirmButton.tsx
  src/components/Map/MapSearchForm.tsx
  src/components/Map/MapSearchItem.tsx
  src/components/Map/MapSearchList.tsx
  src/components/Map/MapWrapper.tsx
  src/components/Map/contexts/MapContextProvider.tsx
  src/components/Map/hooks/index.ts
  src/components/Map/hooks/useMap.ts
  src/components/Map/hooks/useMapListMarkers.ts
  src/components/Map/hooks/useMapPickMarker.ts
  src/components/Map/hooks/useMapSearchForm.ts
  src/components/Map/hooks/useSearchList.ts
  src/components/Map/index.ts
  src/components/Map/utils/mapMarkerUtils.ts
Labels: enhancement

#111 Feature/fe-081: 수정 페이지 추가 및 로직 변경
  .github/workflows/testing.yml
  src/api/index.ts
  src/api/write/api.ts
  src/api/write/hooks/index.ts
  src/api/write/hooks/useGetBoard.ts
  src/api/write/hooks/usePatchBoard.ts
  src/api/write/index.ts
  src/api/write/queryKeys.ts
  src/app/board/components/DetailMenuButton/DetailMenuButton.tsx
  src/app/write/[id]/page.tsx
  src/app/write/components/AgeModal/AgeBottomSheet.tsx
  src/app/write/components/AgeModal/AgeController.tsx
  src/app/write/components/AgeModal/AgeModal.css.ts
  src/app/write/components/AgeModal/AgeModal.tsx
  src/app/write/components/AgeModal/BirthYear.tsx
  src/app/write/components/Counter/Counter.tsx
  src/app/write/components/Form/BoardForm.tsx
  src/app/write/components/Form/FirstStep.tsx
  src/app/write/components/Form/Form.css.ts
  src/app/write/components/Form/SecondStep.tsx
  src/app/write/components/InputDate/InputDate.tsx
  src/app/write/components/InputLoading/InputLoading.css.ts
  src/app/write/components/InputLoading/InputLoading.tsx
  src/app/write/components/MapModal/MapModal.tsx
  src/app/write/components/TimeDropDown/TimeDropDown.tsx
  src/app/write/components/index.ts
  src/app/write/hooks/useSetFormData.ts
  src/app/write/hooks/useWriteForm.ts
  src/app/write/lib/schema.ts
  src/app/write/page.tsx
  src/app/write/store/useFormStore.tsx
  src/app/write/style.css.ts
  src/app/write/types/index.ts
  src/components/BottomSheet/BottomSheet.css.ts
  src/components/BottomSheet/BottomSheetView.tsx
  src/components/DateInput/DateInput.tsx
  src/components/DayPicker/DateCaption.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/DropdownWrapper.tsx
  src/components/Input/Input.css.ts
  src/components/Input/InputDropdown.tsx
  src/components/Input/hook/useForwardRef.ts
  src/hooks/useClickOutside/useClickOutside.ts
Labels: ✨ feature

#122 Feature/fe-086: 폰트 최적화 적용
  public/PretendardVariable.woff2
  public/fonts/Pretendard-Bold.woff2
  public/fonts/Pretendard-Regular.woff2
  public/fonts/Pretendard-Semibold.woff2
  src/app/layout.tsx
Labels: enhancement

#124 Feature/fe-088 : 먹팟 필터링 관련 수정사항 반영
  .pnp.cjs
  .yarn/cache/decode-uri-component-npm-0.4.1-61db093ef6-0473924860.zip
  .yarn/cache/filter-obj-npm-5.1.0-a1ae61a7db-ba7c24d9b2.zip
  .yarn/cache/query-string-npm-8.1.0-e74248e410-16fe49ab71.zip
  .yarn/cache/split-on-first-npm-3.0.0-3b993e48ae-75dc27ecba.zip
  package.json
  src/api/board/api.ts
  src/api/board/hooks/useBoardDetail.ts
  src/api/board/queryKeys.ts
  src/app/board/[id]/page.tsx
  src/app/board/components/ContentSection/ContentSection.tsx
  src/app/board/components/ContentSection/FooterLinkButtons.tsx
  src/app/board/components/HydratedBoardDetail/HydratedBoardDetail.tsx
  src/app/board/hooks/useBoardDetail/useBoardDetail.tsx
  src/app/home/components/BoardCard/BoardCard.tsx
  src/app/home/components/BoardCard/BoardCardLink.tsx
  src/app/home/components/BoardCardList/BoardCardList.tsx
  src/app/home/components/RegionsFilter/RegionsFilter.tsx
  src/components/Logo/Logo.tsx
  src/components/Logo/LogoLink.tsx
  src/store/index.ts
  src/store/store.test.ts
  src/store/store.ts
  src/store/useRegionFilterStore.ts
  src/utils/queryString/index.ts
  src/utils/queryString/queryString.test.ts
  src/utils/queryString/queryString.ts
  yarn.lock
Labels: ✨ feature

#128 Feature/FE-092 : map, 회원가입, 로그인 QA 대응
  src/app/login/components/LoginButton/LoginButton.tsx
  src/app/login/components/LoginWrapper/LoginWrapper.tsx
  src/app/login/contexts/LoginContext.tsx
  src/app/signup/components/AgreeButton/AgreeButton.tsx
  src/app/signup/components/ProfileSetupSignUp/ProfileSetupSignUp.tsx
  src/app/signup/constants/dropdown.ts
  src/app/signup/constants/schema.ts
  src/app/signup/hooks/useConsent/useConsent.ts
  src/components/IconButton/IconButton.tsx
  src/components/Map/Map.css.ts
  src/components/Map/MapConfirmButton.tsx
  src/components/Map/MapSearchList.tsx
  src/components/Map/contexts/MapContextProvider.tsx
  src/components/Map/hooks/index.ts
  src/components/Map/hooks/useMapListMarkers.ts
  src/components/Map/hooks/useMapPickMarker.ts
  src/components/Map/hooks/useMapSearchForm.ts
  src/components/Map/hooks/useSearchList.ts
Labels: 🐞 bug
