Repository YAPP-Github/mukpat-client, pull requests merged in 2023-06, with the labels that each got.

#24 Feature/fe-015: Dropdown
  .eslintrc.json
  package.json
  src/components/Dropdown/Dropdown.css.ts
  src/components/Dropdown/Dropdown.test.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/DropdownButton.tsx
  src/components/Dropdown/DropdownItem.tsx
  src/components/Dropdown/DropdownMenu.tsx
  src/components/Dropdown/DropdownToggle.tsx
  src/components/Dropdown/DropdownWrapper.tsx
  src/components/Dropdown/Icons/CaretDownIcon.tsx
  src/components/Dropdown/Icons/CheckedIcon.tsx
  src/components/Dropdown/README.md
  src/components/Dropdown/contexts/DropdownContext.tsx
  src/components/Dropdown/contexts/DropdownMenuContext.tsx
  src/components/Dropdown/hooks/index.ts
  src/components/Dropdown/hooks/useDropdownOpenState/useDropdownOpenState.test.ts
  src/components/Dropdown/hooks/useDropdownOpenState/useDropdownOpenState.ts
  src/components/Dropdown/hooks/useMenuYPlacement/useMenuYPlacement.test.tsx
  src/components/Dropdown/hooks/useMenuYPlacement/useMenuYPlacement.ts
  src/components/Dropdown/index.ts
  src/components/IconButton/utils/getIconUrl.test.ts
  src/components/index.ts
  src/hooks/index.ts
  src/hooks/useClickOutside/useClickOutside.test.tsx
  src/hooks/useClickOutside/useClickOutside.ts
  src/styles/globals.css.ts
Labels: ✨ feature

#27 Feature/fe-015: Dropdown 수정사항
  src/components/Dropdown/Dropdown.css.ts
  src/components/Dropdown/DropdownMenu.tsx
  src/components/Dropdown/DropdownToggle.tsx
  src/components/Dropdown/README.md
  src/components/Dropdown/contexts/DropdownContext.tsx
  src/components/Dropdown/hooks/index.ts
  src/components/Dropdown/hooks/useDropdownOpenState/useDropdownOpenState.test.ts
  src/components/Dropdown/hooks/useDropdownOpenState/useDropdownOpenState.ts
  src/components/Dropdown/hooks/useMenuYPlacement/useMenuYPlacement.ts
  src/components/Dropdown/utils/placement.test.ts
  src/components/Dropdown/utils/placement.ts
  src/hooks/index.ts
  src/hooks/useBooleanState/useBooleanState.test.ts
  src/hooks/useBooleanState/useBooleanState.ts
  src/hooks/useIsOpen/useIsOpen.test.ts
  src/hooks/useIsOpen/useIsOpen.ts
Labels: enhancement, ✨ feature

#25 Feature/fe-030: SegmentedControl
  .pnp.cjs
  .yarn/cache/@emotion-is-prop-valid-npm-0.8.8-261a0f2426-bb7ec6d48c.zip
  .yarn/cache/@emotion-memoize-npm-0.7.4-5648cf11b8-4e3920d4ec.zip
  .yarn/cache/framer-motion-npm-10.12.16-15fa41631a-0ba346fd6e.zip
  package.json
  src/components/SegmentedControl/README.md
  src/components/SegmentedControl/SegmentedControl.css.ts
  src/components/SegmentedControl/SegmentedControl.test.tsx
  src/components/SegmentedControl/SegmentedControl.tsx
  src/components/SegmentedControl/SegmentedControlItem.tsx
  src/components/index.ts
  yarn.lock
Labels: ✨ feature

#28 Feature/fe-028 : IconSprite 적용
  .pnp.cjs
  .yarn/cache/boolbase-npm-1.0.0-965fe9af6d-3e25c80ef6.zip
  .yarn/cache/cheerio-npm-1.0.0-rc.10-7461d63143-ace2f9c580.zip
  .yarn/cache/cheerio-select-npm-1.6.0-52d6f4bd1e-c64cccea5b.zip
  .yarn/cache/css-select-npm-4.3.0-72f53028ec-d620273683.zip
  .yarn/cache/css-what-npm-6.1.0-57f751efbb-b975e547e1.zip
  .yarn/cache/dom-serializer-npm-1.4.1-ebb24349c1-fbb0b01f87.zip
  .yarn/cache/domelementtype-npm-2.3.0-02de7cbfba-ee837a318f.zip
  .yarn/cache/domhandler-npm-4.3.1-493539c1ca-4c665ceed0.zip
  .yarn/cache/domutils-npm-2.8.0-0325139e5c-abf7434315.zip
  .yarn/cache/entities-npm-2.2.0-0fc8d5b2f7-19010dacaf.zip
  .yarn/cache/htmlparser2-npm-6.1.0-4ef89ab31e-81a7b3d9c3.zip
  .yarn/cache/nth-check-npm-2.1.1-f97afc8169-5afc3dafcd.zip
  .yarn/cache/parse5-htmlparser2-tree-adapter-npm-6.0.1-60b4888f75-1848378b35.zip
  .yarn/cache/parse5-npm-6.0.1-70a35a494a-7d569a176c.zip
  .yarn/cache/svgstore-cli-npm-2.0.1-de4afd8eb0-1d0795f191.zip
  .yarn/cache/svgstore-npm-3.0.1-e6e13e20f0-08ad27f927.zip
  .yarn/cache/tslib-npm-2.5.3-7756051e02-88902b309a.zip
  .yarn/cache/yargs-parser-npm-20.2.9-a1d19e598d-8bb69015f2.zip
  package.json
  public/sprite.svg
  public/spriteIcons/calendar.svg
  public/spriteIcons/chat.svg
  public/spriteIcons/check-active.svg
  public/spriteIcons/check-error.svg
  public/spriteIcons/check-hover.svg
  public/spriteIcons/check.svg
  public/spriteIcons/chevronleft-disable.svg
  public/spriteIcons/chevronleft-hover.svg
  public/spriteIcons/chevronleft.svg
  public/spriteIcons/chevronright-disable.svg
  public/spriteIcons/chevronright-hover.svg
  public/spriteIcons/chevronright.svg
  public/spriteIcons/close-hover.svg
  public/spriteIcons/close.svg
  public/spriteIcons/copy-hover.svg
  public/spriteIcons/copy.svg
  public/spriteIcons/dot-hover.svg
  public/spriteIcons/dot.svg
  public/spriteIcons/link-hover.svg
  public/spriteIcons/link.svg
  public/spriteIcons/map.svg
  public/spriteIcons/minus-disable.svg
  public/spriteIcons/minus-hover.svg
  public/spriteIcons/minus.svg
  public/spriteIcons/plus-hover.svg
  public/spriteIcons/plus.svg
  public/spriteIcons/search.svg
  src/app/layout.tsx
  src/app/page.tsx
  src/components/SvgIcon/SvgIcon.tsx
  src/components/index.ts
  yarn.lock
Labels: ✨ feature

#32 Feature/fe-031 : Typography 추가 작업
  src/components/Typography/Typography.css.ts
  src/components/Typography/Typography.tsx
Labels: ✨ feature

#41 Feature/fe-034 : DateInput 컴포넌트
  .pnp.cjs
  .yarn/cache/@babel-runtime-npm-7.22.5-0a6711d04c-12a50b7de2.zip
  .yarn/cache/date-fns-npm-2.30.0-895c790e0f-f7be015232.zip
  .yarn/cache/react-day-picker-npm-8.7.1-2e9e6afbdd-ae5fa4d581.zip
  package.json
  src/components/DateInput/DateCaption.tsx
  src/components/DateInput/DateInput.css.ts
  src/components/DateInput/DateInput.tsx
  src/components/DateInput/README.md
  src/components/DateInput/utils/caption.test.ts
  src/components/DateInput/utils/caption.ts
  src/components/Dropdown/Dropdown.css.ts
  src/components/Dropdown/Dropdown.test.tsx
  src/components/Dropdown/DropdownButton.tsx
  src/components/Dropdown/DropdownMenu.tsx
  src/components/Dropdown/README.md
  src/components/index.ts
  yarn.lock
Labels: ✨ feature

#38 Feature/fe-010 : Input 컴포넌트
  .pnp.cjs
  .prettierrc
  .yarn/cache/@hookform-resolvers-npm-3.1.0-8f7cf259db-8f6690e514.zip
  .yarn/cache/@types-react-npm-18.2.8-b0b52e84d7-351fe2450d.zip
  .yarn/cache/@types-react-npm-18.2.9-53fdc3302c-f155256171.zip
  .yarnrc.yml
  package.json
  public/icons/caretdown/default.svg
  public/icons/clear/default.svg
  public/sprite.svg
  public/spriteIcons/caretdown.svg
  public/spriteIcons/clear.svg
  src/components/Form/Form.css.ts
  src/components/Form/FormErrorMessage.tsx
  src/components/Form/SubmitButton.tsx
  src/components/Input/Input.css.ts
  src/components/Input/Input.tsx
  src/components/Input/InputDropdown.tsx
  src/components/Input/InputErrorMessage.tsx
  src/components/Input/InputSection.tsx
  src/components/Input/Readme.md
  src/components/Input/TextArea.tsx
  src/components/Input/hook/useForwardRef.ts
  src/components/Input/index.ts
  src/components/Input/schema.ts
  src/components/Modal/Modal.css.ts
  src/components/Modal/Modal.test.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/ModalContent.tsx
  src/components/Modal/ModalFooter.tsx
  src/components/Modal/ModalHeader.tsx
  src/components/index.ts
  src/styles/globals.css.ts
  src/utils/getIconUrl/getIconUrl.ts
  yarn.lock
Labels: ✨ feature

#42 Feature/fe-016: Header 컴포넌트
  .gitignore
  .pnp.cjs
  .yarn/cache/@vanilla-extract-css-utils-npm-0.1.3-5d3d0d7795-fa6c28d3f6.zip
  next.config.js
  package.json
  public/sprite.svg
  public/spriteIcons/chevrondown.svg
  src/app/error.tsx
  src/app/login/components/LoginForm/LoginForm.tsx
  src/app/login/components/index.ts
  src/app/login/hooks/useLoginForm.ts
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/post/components/Post/Post.server.tsx
  src/app/post/components/Post/Post.test.tsx
  src/app/post/components/Post/Post.tsx
  src/app/post/components/index.ts
  src/app/post/hooks/index.ts
  src/app/post/hooks/queries/posts/posts.test.ts
  src/app/post/hooks/queries/posts/posts.ts
  src/app/post/page.tsx
  src/components/Badge/Badge.css.ts
  src/components/Badge/Badge.test.tsx
  src/components/Badge/Badge.tsx
  src/components/Content/Content.css.ts
  src/components/Content/Content.tsx
  src/components/Header/Header.css.ts
  src/components/Header/Header.test.tsx
  src/components/Header/Header.tsx
  src/components/Header/HeaderWrapper.tsx
  src/components/Header/LoginActions.tsx
  src/components/Header/UnloginActions.tsx
  src/components/Logo/Logo.css.ts
  src/components/Logo/Logo.tsx
  src/components/index.ts
  src/components/server.ts
  src/hooks/index.ts
  src/hooks/useIntersectObserver/useIntersectObserver.ts
  src/styles/globals.css.ts
  src/types/data.ts
  src/utils/ky/hooks/processError.ts
  src/utils/ky/hooks/processResponse.ts
  src/utils/ky/hooks/setupCookies.ts
  src/utils/ky/request.ts
  tsconfig.json
  yarn.lock
Labels: ✨ feature

#44 Feature/fe-035 : CheckBox 컴포넌트
  public/icons/check/active.svg
  public/icons/check/default.svg
  public/icons/check/error.svg
  public/icons/check/hover.svg
  public/sprite.svg
  public/spriteIcons/check-active.svg
  public/spriteIcons/check-error.svg
  public/spriteIcons/check-hover.svg
  public/spriteIcons/check.svg
  src/components/CheckBox/CheckBox.css.ts
  src/components/CheckBox/CheckBox.tsx
  src/components/CheckBox/README.md
  src/components/CheckBox/utils/getIconId/getIconId.test.ts
  src/components/CheckBox/utils/getIconId/getIconId.ts
  src/components/CheckBox/utils/index.ts
  src/components/Dropdown/README.md
  src/components/Dropdown/index.ts
  src/components/index.ts
Labels: ✨ feature

#51 Feature/fe-010 : Input 컴포넌트 수정
  src/components/Input/Input.css.ts
  src/components/Input/InputSection.tsx
Labels: enhancement
